[package]
name = "execution"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }

[lib]
name = "execution"
path = "src/lib.rs"

[dependencies]
arrow = "50"
