[package]
name = "physical-operator"
version = {workspace=true}
edition = {workspace=true}

[lib]
name="physical_operator"
path="src/lib.rs"

[dependencies]
arrow = {workspace=true}
execution = {workspace=true}
physical-expr = {workspace=true}
